### ISSUE TITLE
DataTimeOffSet serialization

### ISSUE THREAD

**Issue by artijoshi-spec** [Dasync/Dasync#6]
Trying to plugin Dasync in-memory is giving error in serializing DataTimeOffSet- Dasync.Serialization.UnserializableTypeException: 'Cannot serialize type 'System.DateTimeOffset. Any idea how to go pass it?

These are the bindings added:             
services.AddModules(
                Dasync.Modeling.DI.Bindings,
                Dasync.Serialization.DI.Bindings,
                Dasync.Serialization.Json.DI.Bindings,
                Dasync.Serializers.StandardTypes.DI.Bindings,
                Dasync.Serializers.EETypes.DI.Bindings,
                Dasync.Serializers.DomainTypes.DI.Bindings,
                Dasync.Proxy.DI.Bindings,
                Dasync.AsyncStateMachine.DI.Bindings,
                Dasync.ExecutionEngine.DI.Bindings,
                Dasync.DependencyInjection.DI.Bindings);

            services.AddModule(Dasync.Fabric.Sample.Base.DI.Bindings);
            services.AddModule(Dasync.Fabric.InMemory.DI.Bindings);

**Comment by kind-serge** [comment]
Hi @artijoshi-spec, you already have the `Dasync.Serializers.StandardTypes.DI.Bindings` added to the IoC container, and it should work. I was not able to repro using samples provided in this repo.

Can you provide with a sample code that uses `DateTimeOffset` and the serialization fails?

**Comment by artijoshi-spec** [comment]
Yes- I got it working. Thanks for getting back. One question on the Unit of work integration with in-memory fabric,  is there an implementation similar to what development environment utilizes along the lines of 
    internal class RoutineTransitionAction : IRoutineTransitionAction
    {
        private readonly IUnitOfWork _unitOfWork;

        public RoutineTransitionAction(IEnumerable<IUnitOfWork> unitOfWorks)
        {
            _unitOfWork = unitOfWorks.FirstOrDefault();
        }

        public ValueTask OnRoutineStartAsync(IServiceDefinition serviceDefinition, ServiceId serviceId, RoutineMethodId methodId, string routineId)
        {
            _unitOfWork?.StartNew();
            return new ValueTask();
        }

        public async ValueTask OnRoutineCompleteAsync(IServiceDefinition serviceDefinition, ServiceId serviceId, RoutineMethodId methodId, string routineId, TaskResult result)
        {
            if (_unitOfWork != null)
                await _unitOfWork.CommitAsync(routineId);
        }

I tried importing bindings for development fabric in our solution which includes this class, but I don't see it getting called, how can I enable unit of work with in-memory fabric?
Let me know if this deserves its own thread.

**Comment by kind-serge** [comment]
The InMemory fabric was made for demo purposes only and does not have parity with the ones you have for production and local development. It will be completely re-built with the new internal design of D-ASYNC version 2.

If this is something you need right now in v1, you can modify [the code that triggers a method to run](https://github.com/Dasync/Dasync/blob/master/Fabric/Fabric.InMemory/InMemoryFabric.cs#L159).
